####################################################
#                                                  #
#       Welcome To docker file configuration       #
#                                                  #
####################################################

#This file for hosting our project php api we dont need that now 

#Defines image php apache the webserver apache support php 
FROM php:8.2-apache

#We need to install pdo extensions to work with database
RUN docker-php-ext-install pdo pdo_mysql

# Copy application code to the webserver directory
COPY . /var/www/html

# Set proper permissions for the webserver
RUN chown -R www-data:www-data /var/www/html \
    && chmod -R 755 /var/www/html

# Expose the default Apache HTTP port
EXPOSE 80

# Start Apache server
CMD ["apache2-foreground"]


